apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hhf5hpniu-go
  janus-idp.io/tekton: hhf5hpniu-go
  backstage.io/kubernetes-id: hhf5hpniu-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hhf5hpniu-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
