apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hhf5hpniu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hhf5hpniu-go 
  name: hhf5hpniu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hhf5hpniu-go 
