apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hhf5hpniu-go-gitops
  description: This is GitOps manifest for hhf5hpniu-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=hhf5hpniu-go
    backstage.io/kubernetes-id: hhf5hpniu-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: hhf5hpniu-go-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hhf5hpniu-go
